// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.17020
//


/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="AdminServiceSoap", Namespace="http://api.channeladvisor.com/webservices/")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AdminService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private APICredentials APICredentialsValueField;
    
    private System.Threading.SendOrPostCallback GetAuthorizationListOperationCompleted;
    
    private System.Threading.SendOrPostCallback RequestAccessOperationCompleted;
    
    private System.Threading.SendOrPostCallback PingOperationCompleted;
    

	public AdminService() {
        this.Url = "https://api.channeladvisor.com/ChannelAdvisorAPI/v7/AdminService.asmx";
    }

	public AdminService(string devkey, string devPass){
		APICredentialsValue.DeveloperKey = devkey;
		APICredentialsValue.Password = devPass;
	}
    
    public APICredentials APICredentialsValue {
        get {
            return this.APICredentialsValueField;
        }
        set {
            this.APICredentialsValueField = value;
        }
    }

	static public AdminService getInstance(string devkey, string devPass){
		return new AdminService (devkey, devPass);
	}
    
    public event GetAuthorizationListCompletedEventHandler GetAuthorizationListCompleted;
    
    public event RequestAccessCompletedEventHandler RequestAccessCompleted;
    
    public event PingCompletedEventHandler PingCompleted;
    
    [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/GetAuthorizationList", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public APIResultOfArrayOfAuthorizationResponse GetAuthorizationList([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string localID) {
        object[] results = this.Invoke("GetAuthorizationList", new object[] {
                    localID});
        return ((APIResultOfArrayOfAuthorizationResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginGetAuthorizationList(string localID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAuthorizationList", new object[] {
                    localID}, callback, asyncState);
    }
    
    public APIResultOfArrayOfAuthorizationResponse EndGetAuthorizationList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((APIResultOfArrayOfAuthorizationResponse)(results[0]));
    }
    
    public void GetAuthorizationListAsync(string localID) {
        this.GetAuthorizationListAsync(localID, null);
    }
    
    public void GetAuthorizationListAsync(string localID, object userState) {
        if ((this.GetAuthorizationListOperationCompleted == null)) {
            this.GetAuthorizationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizationListCompleted);
        }
        this.InvokeAsync("GetAuthorizationList", new object[] {
                    localID}, this.GetAuthorizationListOperationCompleted, userState);
    }
    
    private void OnGetAuthorizationListCompleted(object arg) {
        if ((this.GetAuthorizationListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAuthorizationListCompleted(this, new GetAuthorizationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValueField")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/RequestAccess", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public APIResultOfBoolean RequestAccess(int localID) {
        object[] results = this.Invoke("RequestAccess", new object[] {
                    localID});
        return ((APIResultOfBoolean)(results[0]));
    }
    
    public System.IAsyncResult BeginRequestAccess(int localID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RequestAccess", new object[] {
                    localID}, callback, asyncState);
    }
    
    public APIResultOfBoolean EndRequestAccess(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((APIResultOfBoolean)(results[0]));
    }
    
    public void RequestAccessAsync(int localID) {
        this.RequestAccessAsync(localID, null);
    }
    
    public void RequestAccessAsync(int localID, object userState) {
        if ((this.RequestAccessOperationCompleted == null)) {
            this.RequestAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestAccessCompleted);
        }
        this.InvokeAsync("RequestAccess", new object[] {
                    localID}, this.RequestAccessOperationCompleted, userState);
    }
    
    private void OnRequestAccessCompleted(object arg) {
        if ((this.RequestAccessCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RequestAccessCompleted(this, new RequestAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValueField")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/Ping", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public APIResultOfString Ping() {
        object[] results = this.Invoke("Ping", new object[0]);
        return ((APIResultOfString)(results[0]));
    }
    
    public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Ping", new object[0], callback, asyncState);
    }
    
    public APIResultOfString EndPing(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((APIResultOfString)(results[0]));
    }
    
    public void PingAsync() {
        this.PingAsync(null);
    }
    
    public void PingAsync(object userState) {
        if ((this.PingOperationCompleted == null)) {
            this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
        }
        this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
    }
    
    private void OnPingCompleted(object arg) {
        if ((this.PingCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
public partial class APIResultOfArrayOfAuthorizationResponse {
    
    private ResultStatus statusField;
    
    private int messageCodeField;
    
    private string messageField;
    
    private string dataField;
    
    private AuthorizationResponse[] resultDataField;
    
    /// <remarks/>
    public ResultStatus Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public int MessageCode {
        get {
            return this.messageCodeField;
        }
        set {
            this.messageCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public AuthorizationResponse[] ResultData {
        get {
            return this.resultDataField;
        }
        set {
            this.resultDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
public enum ResultStatus {
    
    /// <remarks/>
    Success,
    
    /// <remarks/>
    Failure,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
public partial class AuthorizationResponse {
    
    private string accountIDField;
    
    private int localIDField;
    
    private string accountNameField;
    
    private string accountTypeField;
    
    private string resourceNameField;
    
    private string statusField1;
    
    /// <remarks/>
    public string AccountID {
        get {
            return this.accountIDField;
        }
        set {
            this.accountIDField = value;
        }
    }
    
    /// <remarks/>
    public int LocalID {
        get {
            return this.localIDField;
        }
        set {
            this.localIDField = value;
        }
    }
    
    /// <remarks/>
    public string AccountName {
        get {
            return this.accountNameField;
        }
        set {
            this.accountNameField = value;
        }
    }
    
    /// <remarks/>
    public string AccountType {
        get {
            return this.accountTypeField;
        }
        set {
            this.accountTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ResourceName {
        get {
            return this.resourceNameField;
        }
        set {
            this.resourceNameField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField1;
        }
        set {
            this.statusField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.channeladvisor.com/webservices/", IsNullable=true)]
public partial class APICredentials : System.Web.Services.Protocols.SoapHeader {
    
    private string developerKeyField;
    
    private string passwordField;
    
    private System.Xml.XmlAttribute[] anyAttributeField;
    
    /// <remarks/>
    public string DeveloperKey {
        get {
            return this.developerKeyField;
        }
        set {
            this.developerKeyField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttribute()]
    public virtual System.Xml.XmlAttribute[] AnyAttribute {
        get {
            return this.anyAttributeField;
        }
        set {
            this.anyAttributeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
public partial class APIResultOfBoolean {
    
    private ResultStatus statusField2;
    
    private int messageCodeField1;
    
    private string messageField1;
    
    private string dataField1;
    
    private bool resultDataField1;
    
    /// <remarks/>
    public ResultStatus Status {
        get {
            return this.statusField2;
        }
        set {
            this.statusField2 = value;
        }
    }
    
    /// <remarks/>
    public int MessageCode {
        get {
            return this.messageCodeField1;
        }
        set {
            this.messageCodeField1 = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField1;
        }
        set {
            this.messageField1 = value;
        }
    }
    
    /// <remarks/>
    public string Data {
        get {
            return this.dataField1;
        }
        set {
            this.dataField1 = value;
        }
    }
    
    /// <remarks/>
    public bool ResultData {
        get {
            return this.resultDataField1;
        }
        set {
            this.resultDataField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
public partial class APIResultOfString {
    
    private ResultStatus statusField3;
    
    private int messageCodeField2;
    
    private string messageField2;
    
    private string dataField2;
    
    private string resultDataField2;
    
    /// <remarks/>
    public ResultStatus Status {
        get {
            return this.statusField3;
        }
        set {
            this.statusField3 = value;
        }
    }
    
    /// <remarks/>
    public int MessageCode {
        get {
            return this.messageCodeField2;
        }
        set {
            this.messageCodeField2 = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField2;
        }
        set {
            this.messageField2 = value;
        }
    }
    
    /// <remarks/>
    public string Data {
        get {
            return this.dataField2;
        }
        set {
            this.dataField2 = value;
        }
    }
    
    /// <remarks/>
    public string ResultData {
        get {
            return this.resultDataField2;
        }
        set {
            this.resultDataField2 = value;
        }
    }
}

public partial class GetAuthorizationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAuthorizationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public APIResultOfArrayOfAuthorizationResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((APIResultOfArrayOfAuthorizationResponse)(this.results[0]));
        }
    }
}

public delegate void GetAuthorizationListCompletedEventHandler(object sender, GetAuthorizationListCompletedEventArgs args);

public partial class RequestAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RequestAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public APIResultOfBoolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((APIResultOfBoolean)(this.results[0]));
        }
    }
}

public delegate void RequestAccessCompletedEventHandler(object sender, RequestAccessCompletedEventArgs args);

public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public APIResultOfString Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((APIResultOfString)(this.results[0]));
        }
    }
}

public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs args);
